var albums = [
  { type: "album",
    albumTitle: "Album 1",
    albumRel: "album-1",
    albumCover: "images/album\ 1/lowResPhotos/photo1.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 1/lowResPhotos/photo1.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo1.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 1/lowResPhotos/photo2\ copy.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo2.jpeg",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 1/lowResPhotos/photo3\ copy.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo3.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 1/lowResPhotos/photo4\ copy.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo4.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 1/lowResPhotos/photo5\ copy.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo5.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 1/lowResPhotos/photo6\ copy.jpeg",
          photoFull: "images/album\ 1/highResPhotos/photo6.jpeg",
        },
      ],
  },
  { type: "album",
    albumTitle: "Album 2",
    albumRel: "album-2",
    albumCover: "images/album\ 2/lowResPhotos/photo1\ copy.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 2/lowResPhotos/photo1\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo1.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 2/lowResPhotos/photo2\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo2.jpeg",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 2/lowResPhotos/photo3\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo3.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 2/lowResPhotos/photo4\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo4.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 2/lowResPhotos/photo5\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo5.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 2/lowResPhotos/photo6\ copy.jpeg",
          photoFull: "images/album\ 2/highResPhotos/photo6.jpeg",
        },
      ],
  },
  { type: "album",
    albumTitle: "Album 3",
    albumRel: "album-3",
    albumCover: "images/album\ 3/lowResPhoto/photo1\ copy.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 3/lowResPhoto/photo1\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo1.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 3/lowResPhoto/photo2\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo2.jpeg",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 3/lowResPhoto/photo3\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo3.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 3/lowResPhoto/photo4\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo4.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 3/lowResPhoto/photo5\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo5.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 3/lowResPhoto/photo6\ copy.jpeg",
          photoFull: "images/album\ 3/highResPhoto/photo6.jpeg",
        },
      ],
  },
  { type: "album",
    albumTitle: "Album 4",
    albumRel: "album-4",
    albumCover: "images/album\ 4/lowResPhotos/photo1\ copy.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 4/lowResPhotos/photo1\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo1.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 4/lowResPhotos/photo2\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo2.jpeg",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 4/lowResPhotos/photo3\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo3.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 4/lowResPhotos/photo4\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo4.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 4/lowResPhotos/photo5\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo5.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 4/lowResPhotos/photo6\ copy.jpeg",
          photoFull: "images/album\ 4/highResPhotos/photo6.jpeg",
        },
      ],
  },
  { type: "album",
    albumTitle: "Album 5",
    albumRel: "album-5",
    albumCover: "images/album\ 5/lowResPhotos/photo1.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 5/lowResPhotos/photo1.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo1\ copy.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 5/lowResPhotos/photo2.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo2\ copy",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 5/lowResPhotos/photo3.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo3\ copy.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 5/lowResPhotos/photo4.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo4\ copy.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 5/lowResPhotos/photo5.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo5\ copy.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 5/lowResPhotos/photo6.jpeg",
          photoFull: "images/album\ 5/highResPhotos/photo6\ copy.jpeg",
        },
      ],
  },
  { type: "album",
    albumTitle: "Album 6",
    albumRel: "album-6",
    albumCover: "images/album\ 6/lowResPhotos/photo1\ copy.jpeg",
      photos: [
        { photoName: "Photo 1",
          photoRel: "photo-1",
          photoThumb: "images/album\ 6/lowResPhotos/photo1\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo1.jpeg",
        },
        { photoName: "Photo 2",
          photoRel: "photo-2",
          photoThumb: "images/album\ 6/lowResPhotos/photo2\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo2.jpeg",
        },
        { photoName: "Photo 3",
          photoRel: "photo-3",
          photoThumb: "images/album\ 6/lowResPhotos/photo3\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo3.jpeg",
        },
        { photoName: "Photo 4",
          photoRel: "photo-4",
          photoThumb: "images/album\ 6/lowResPhotos/photo4\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo4.jpeg",
        },
        { photoName: "Photo 5",
          photoRel: "photo-5",
          photoThumb: "images/album\ 6/lowResPhotos/photo5\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo5.jpeg",
        },
        { photoName: "Photo 6",
          photoRel: "photo-6",
          photoThumb: "images/album\ 6/lowResPhotos/photo6\ copy.jpeg",
          photoFull: "images/album\ 6/highResPhotos/photo6.jpeg",
        },
      ],
  },
]
